<?php

		// Exit if accessed directly
		if ( ! defined( 'ABSPATH' ) ) {
			exit;
		}

		function fusion_builder_add_photography_demo( $demos ) {

		$demos['photography'] = array (
  'category' => 'Avada Photography',
  'pages' => 
  array (
     
    array (
      'name' => 'Home',
      'page_template' => '100-width.php',
      'content' => '[fusion_builder_container background_color="" background_image="" background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_url="" video_aspect_ratio="16:9" video_webm="" video_mp4="" video_ogv="" video_preview_image="" overlay_color="" video_mute="yes" video_loop="yes" fade="no" border_size="0px" border_color="" border_style="solid" padding_top="20px" padding_bottom="2.5%" padding_left="" padding_right="" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" menu_anchor="" class="" id=""][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" last="yes" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="0% 15%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height=""][fusion_text]
<h3 style="text-align: center;">CAPTURING MOMENTS AS THEY HAPPEN</h3>
[/fusion_text][fusion_text]
<p style="text-align: center;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
[/fusion_text][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container hundred_percent="yes" equal_height_columns="no" menu_anchor="" hide_on_mobile="no" class="" id="" background_color="" background_image="" background_position="left top" background_repeat="no-repeat" fade="no" background_parallax="none" enable_mobile="no" parallax_speed="0.3" video_mp4="" video_webm="" video_ogv="" video_url="" video_aspect_ratio="16:9" video_loop="yes" video_mute="yes" overlay_color="" video_preview_image="" border_size="0px" border_color="" border_style="solid" margin_top="" margin_bottom="" padding_top="0px" padding_right="4%" padding_bottom="100px" padding_left="4%"][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" background_position="left top" background_color="" border_size="" border_color="" border_style="solid" spacing="yes" background_image="" background_repeat="no-repeat" padding="" margin_top="0px" margin_bottom="0px" class="" id="" animation_type="" animation_speed="0.3" animation_direction="left" hide_on_mobile="no" center_content="no" min_height="none" last="no" hover_type="none" link="" border_position="all"][fusion_portfolio layout="grid-with-text" picture_size="auto" boxed_text="boxed" columns="4" one_column_text_position="below" column_spacing="40" portfolio_title_display="title" portfolio_text_alignment="center" portfolio_layout_padding="20px 20px 15px 20px" filters="no" cat_slug="" exclude_cats="" number_posts="8" pagination_type="none" offset="" content_length="excerpt" excerpt_length="0" strip_html="yes" carousel_layout="title_on_rollover" scroll_items="" autoplay="no" show_nav="yes" mouse_scroll="no" hide_on_mobile="small-visibility,medium-visibility,large-visibility" class="" id="" animation_type="" animation_direction="down" animation_speed="0.1" animation_offset="" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]',
      'meta' => 
      array (
        'pyre_demo_slider' => 'photography-home',
        'pyre_portfolio_width_100' => 'no',
        'pyre_portfolio_content_length' => 'default',
        'pyre_portfolio_excerpt' => '',
        'pyre_portfolio_filters' => 'yes',
        'pyre_portfolio_text_layout' => 'default',
        'pyre_portfolio_featured_image_size' => 'default',
        'pyre_portfolio_column_spacing' => '',
        'pyre_slider_type' => 'flex',
        'pyre_slider' => '0',
        'pyre_wooslider' => 'photography-home',
        'pyre_revslider' => '0',
        'pyre_elasticslider' => '0',
        'pyre_slider_position' => 'default',
        'pyre_avada_rev_styles' => 'default',
        'pyre_fallback' => '',
        'pyre_main_top_padding' => '',
        'pyre_main_bottom_padding' => '',
        'pyre_hundredp_padding' => '',
        'pyre_show_first_featured_image' => 'no',
        'pyre_display_header' => 'yes',
        'pyre_header_100_width' => 'default',
        'pyre_header_bg_color' => '',
        'pyre_header_bg_opacity' => '',
        'pyre_header_bg' => '',
        'pyre_header_bg_full' => 'no',
        'pyre_header_bg_repeat' => 'repeat',
        'pyre_displayed_menu' => 'default',
        'pyre_display_footer' => 'default',
        'pyre_display_copyright' => 'default',
        'pyre_footer_100_width' => 'default',
        'pyre_sidebar_position' => 'default',
        'pyre_sidebar_bg_color' => '',
        'pyre_page_bg_layout' => 'default',
        'pyre_page_bg_color' => '',
        'pyre_page_bg' => '',
        'pyre_page_bg_full' => 'no',
        'pyre_page_bg_repeat' => 'repeat',
        'pyre_wide_page_bg_color' => '',
        'pyre_wide_page_bg' => '',
        'pyre_wide_page_bg_full' => 'no',
        'pyre_wide_page_bg_repeat' => 'repeat',
        'pyre_page_title' => 'default',
        'pyre_page_title_breadcrumbs_search_bar' => 'default',
        'pyre_page_title_text' => 'default',
        'pyre_page_title_text_alignment' => 'default',
        'pyre_page_title_custom_text' => '',
        'pyre_page_title_text_size' => '',
        'pyre_page_title_custom_subheader' => '',
        'pyre_page_title_custom_subheader_text_size' => '',
        'pyre_page_title_font_color' => '',
        'pyre_page_title_100_width' => 'default',
        'pyre_page_title_height' => '',
        'pyre_page_title_mobile_height' => '',
        'pyre_page_title_bar_bg_color' => '',
        'pyre_page_title_bar_borders_color' => '',
        'pyre_page_title_bar_bg' => '',
        'pyre_page_title_bar_bg_retina' => '',
        'pyre_page_title_bar_bg_full' => 'default',
        'pyre_page_title_bg_parallax' => 'default',
      ),
    ),
     
    array (
      'name' => 'About Me',
      'page_template' => '100-width.php',
      'content' => '[fusion_builder_container background_color="" background_image="" background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_url="" video_aspect_ratio="16:9" video_webm="" video_mp4="" video_ogv="" video_preview_image="" overlay_color="" video_mute="yes" video_loop="yes" fade="no" border_size="0px" border_color="" border_style="solid" padding_top="20px" padding_bottom="2.5%" padding_left="" padding_right="" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" menu_anchor="" class="" id=""][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" last="yes" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="0% 15%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height=""][fusion_text]
<h3 style="text-align: center;">BORN TO SHOOT THE WORLD AROUND ME</h3>
[/fusion_text][fusion_text]
<p style="text-align: center;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
[/fusion_text][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_color="#212326" background_image="" background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_url="" video_aspect_ratio="16:9" video_webm="" video_mp4="" video_ogv="" video_preview_image="" overlay_color="" video_mute="yes" video_loop="yes" fade="no" border_size="0px" border_color="" border_style="solid" padding_top="160px" padding_bottom="100px" padding_left="" padding_right="" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" menu_anchor="" class="" id=""][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" last="yes" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="" margin_top="" margin_bottom="65px" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="top-into-view" class="" id="" min_height=""][fusion_imageframe lightbox="no" gallery_id="" lightbox_image="" style_type="none" hover_type="none" bordercolor="rgba(255,255,255,.2)" bordersize="" borderradius="4px" stylecolor="" align="none" link="" linktarget="_self" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" hide_on_mobile="no" class="" id=""] <img src="https://placehold.it/1170x451" alt="" />[/fusion_imageframe][/fusion_builder_column][fusion_builder_column type="1_2" layout="1_2" last="no" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="0% 9%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="top-into-view" class="" id="" min_height=""][fusion_text]
<h3>Always Searching For The Shot</h3>
[/fusion_text][fusion_text]Aliquam interdum neque non quam scelerisque efficitur. Ut sagittis, mi sed vestibulum bibendum, lacus lacus vulputate enim, vel posuere diam nibh sit amet velit. Vivamus pulvinar sit amet enim sed sagittis. Ut quis porttitor lacus. Nulla tris cursus. Pellentesque molis velit eu bidum.[/fusion_text][/fusion_builder_column][fusion_builder_column type="1_2" layout="1_2" last="yes" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="2% 9% 0% 9%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="top-into-view" class="" id="" min_height=""][fusion_progress height="" text_position="" percentage="88" show_percentage="" unit="" filledcolor="" filledbordercolor="" filledbordersize="" unfilledcolor="" striped="no" animated_stripes="no" textcolor="" class="" id=""]Landscapes[/fusion_progress][fusion_separator style_type="none" top_margin="5" bottom_margin="5" sep_color="" border_size="" icon="" icon_circle="" icon_circle_color="" width="" alignment="center" class="" id="" /][fusion_progress height="" text_position="" percentage="93" show_percentage="" unit="" filledcolor="" filledbordercolor="" filledbordersize="" unfilledcolor="" striped="no" animated_stripes="no" textcolor="" class="" id=""]Wildlife[/fusion_progress][fusion_separator style_type="none" top_margin="5" bottom_margin="5" sep_color="" border_size="" icon="" icon_circle="" icon_circle_color="" width="" alignment="center" class="" id="" /][fusion_progress height="" text_position="" percentage="98" show_percentage="" unit="" filledcolor="" filledbordercolor="" filledbordersize="" unfilledcolor="" striped="no" animated_stripes="no" textcolor="" class="" id=""]Business[/fusion_progress][fusion_separator style_type="none" top_margin="5" bottom_margin="5" sep_color="" border_size="" icon="" icon_circle="" icon_circle_color="" width="" alignment="center" class="" id="" /][fusion_progress height="" text_position="" percentage="84" show_percentage="" unit="" filledcolor="" filledbordercolor="" filledbordersize="" unfilledcolor="" striped="no" animated_stripes="no" textcolor="" class="" id=""]Lifestyle[/fusion_progress][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_color="" background_image="https://placehold.it/2000x1287" background_parallax="up" enable_mobile="no" parallax_speed="0.4" background_repeat="no-repeat" background_position="center center" video_url="" video_aspect_ratio="16:9" video_webm="" video_mp4="" video_ogv="" video_preview_image="" overlay_color="" video_mute="yes" video_loop="yes" fade="no" border_size="0px" border_color="" border_style="solid" padding_top="180px" padding_bottom="150px" padding_left="" padding_right="" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" menu_anchor="" class="" id=""][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" last="yes" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="0% 15%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height=""][fusion_testimonials design="clean" backgroundcolor="transparent" textcolor="#dfdfdf" random="" class="" id=""][fusion_testimonial name="ANSEL ADAMS" avatar="none" image="" image_border_radius="" company="" link="" target="_self"]"When words become unclear, I shall focus with photographs. When images become inadequate, I shall be content with silence."
[/fusion_testimonial][fusion_testimonial name="ERNST HASS" avatar="none" image="" image_border_radius="" company="" link="" target="_self"]"There is only you and your camera. The limitations in your photography are in yourself, for what we see is what we are."
[/fusion_testimonial][fusion_testimonial name="ROBERT FRANK" avatar="none" image="" image_border_radius="" company="" link="" target="_self"]"Black and white are the colors of photography. They symbolize the alternatives of hope and despair to which mankind is subjected."
[/fusion_testimonial][/fusion_testimonials][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_color="#212326" background_image="" background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_url="" video_aspect_ratio="16:9" video_webm="" video_mp4="" video_ogv="" video_preview_image="" overlay_color="" video_mute="yes" video_loop="yes" fade="no" border_size="0px" border_color="" border_style="solid" padding_top="160px" padding_bottom="40px" padding_left="" padding_right="" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" menu_anchor="" class="" id=""][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" last="yes" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="0% 10%" margin_top="" margin_bottom="65px" animation_type="0" animation_direction="down" animation_speed="1" animation_offset="top-into-view" class="" id="" min_height=""][fusion_blog number_posts="" offset="" cat_slug="" exclude_cats="" show_title="yes" title_link="yes" thumbnail="yes" excerpt="yes" excerpt_length="2" meta_all="no" meta_author="yes" meta_categories="yes" meta_comments="yes" meta_date="yes" meta_link="yes" meta_tags="yes" scrolling="pagination" strip_html="yes" blog_grid_columns="3" blog_grid_column_spacing="40" layout="medium" class="" id="" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_color="" background_image="" background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_url="" video_aspect_ratio="16:9" video_webm="" video_mp4="" video_ogv="" video_preview_image="" overlay_color="" video_mute="yes" video_loop="yes" fade="no" border_size="0px" border_color="" border_style="solid" padding_top="100" padding_bottom="0" padding_left="" padding_right="" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" menu_anchor="" class="" id=""][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" last="yes" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="" margin_top="" margin_bottom="0px" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height=""][fusion_title size="3" content_align="center" style_type="none" sep_color="" margin_top="" margin_bottom="" class="" id=""]CLIENTS I\'VE WORKED WITH[/fusion_title][fusion_separator style_type="none" top_margin="40" bottom_margin="" sep_color="" border_size="" icon="" icon_circle="" icon_circle_color="" width="" alignment="center" class="" id="" /][fusion_images picture_size="auto" hover_type="none" autoplay="yes" columns="5" column_spacing="30" scroll_items="1" show_nav="no" mouse_scroll="yes" border="no" lightbox="no" class="" id=""][fusion_image link="" linktarget="_self" image="https://placehold.it/270x160" alt=""/][fusion_image link="" linktarget="_self" image="https://placehold.it/270x160" alt=""/][fusion_image link="" linktarget="_self" image="https://placehold.it/270x160" alt=""/][fusion_image link="" linktarget="_self" image="https://placehold.it/270x160" alt=""/][fusion_image link="" linktarget="_self" image="https://placehold.it/270x160" alt=""/][fusion_image link="" linktarget="_self" image="https://placehold.it/270x160" alt=""/][/fusion_images][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]',
      'meta' => 
      array (
        'pyre_demo_slider' => 'photography-about-me',
        'pyre_portfolio_width_100' => 'no',
        'pyre_portfolio_content_length' => 'default',
        'pyre_portfolio_excerpt' => '',
        'pyre_portfolio_filters' => 'yes',
        'pyre_portfolio_text_layout' => 'default',
        'pyre_portfolio_featured_image_size' => 'default',
        'pyre_portfolio_column_spacing' => '',
        'pyre_portfolio_category' => 'a:1:{i:0;s:1:"0";}',
        'pyre_slider_type' => 'flex',
        'pyre_slider' => '0',
        'pyre_wooslider' => 'photography-about-me',
        'pyre_revslider' => '0',
        'pyre_elasticslider' => '0',
        'pyre_slider_position' => 'default',
        'pyre_avada_rev_styles' => 'default',
        'pyre_fallback' => '',
        'pyre_main_top_padding' => '',
        'pyre_main_bottom_padding' => '',
        'pyre_hundredp_padding' => '',
        'pyre_show_first_featured_image' => 'no',
        'pyre_display_header' => 'yes',
        'pyre_header_100_width' => 'default',
        'pyre_header_bg_color' => '',
        'pyre_header_bg_opacity' => '',
        'pyre_header_bg' => '',
        'pyre_header_bg_full' => 'no',
        'pyre_header_bg_repeat' => 'repeat',
        'pyre_displayed_menu' => 'default',
        'pyre_display_footer' => 'default',
        'pyre_display_copyright' => 'default',
        'pyre_footer_100_width' => 'default',
        'pyre_sidebar_position' => 'default',
        'pyre_sidebar_bg_color' => '',
        'pyre_page_bg_layout' => 'default',
        'pyre_page_bg_color' => '',
        'pyre_page_bg' => '',
        'pyre_page_bg_full' => 'no',
        'pyre_page_bg_repeat' => 'repeat',
        'pyre_wide_page_bg_color' => '',
        'pyre_wide_page_bg' => '',
        'pyre_wide_page_bg_full' => 'no',
        'pyre_wide_page_bg_repeat' => 'repeat',
        'pyre_page_title' => 'default',
        'pyre_page_title_breadcrumbs_search_bar' => 'default',
        'pyre_page_title_text' => 'default',
        'pyre_page_title_text_alignment' => 'default',
        'pyre_page_title_custom_text' => '',
        'pyre_page_title_text_size' => '',
        'pyre_page_title_custom_subheader' => '',
        'pyre_page_title_custom_subheader_text_size' => '',
        'pyre_page_title_font_color' => '',
        'pyre_page_title_100_width' => 'default',
        'pyre_page_title_height' => '',
        'pyre_page_title_mobile_height' => '',
        'pyre_page_title_bar_bg_color' => '',
        'pyre_page_title_bar_borders_color' => '',
        'pyre_page_title_bar_bg' => '',
        'pyre_page_title_bar_bg_retina' => '',
        'pyre_page_title_bar_bg_full' => 'default',
        'pyre_page_title_bg_parallax' => 'default',
      ),
    ),
     
    array (
      'name' => 'Collections',
      'page_template' => '100-width.php',
      'content' => '[fusion_builder_container background_color="" background_image="" background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_url="" video_aspect_ratio="16:9" video_webm="" video_mp4="" video_ogv="" video_preview_image="" overlay_color="" overlay_opacity="0.5" video_mute="yes" video_loop="yes" fade="no" border_size="0px" border_color="" border_style="solid" padding_top="0px" padding_bottom="0px" padding_left="" padding_right="" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" menu_anchor="" class="" id=""][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" last="yes" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="https://placehold.it/1170x300" background_repeat="no-repeat" background_position="center top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="100px 0px" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height=""][fusion_text]
<h4 style="text-align: center; color: #c6c6c6;">FRESH WORKS FROM AROUND THE WORLD</h4>
[/fusion_text][fusion_text]
<h1 style="text-align: center; font-size: 55px; line-height: 65px;">THE AVADA COLLECTION</h1>
[/fusion_text][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_color="" background_image="" background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_url="" video_aspect_ratio="16:9" video_webm="" video_mp4="" video_ogv="" video_preview_image="" overlay_color="" overlay_opacity="0.5" video_mute="yes" video_loop="yes" fade="no" border_size="0px" border_color="" border_style="solid" padding_top="-50px" padding_bottom="100px" padding_left="15%" padding_right="15%" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" menu_anchor="" class="" id=""][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" last="yes" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="" margin_top="-120px" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height=""][fusion_portfolio layout="grid-with-text" picture_size="auto" boxed_text="boxed" columns="2" one_column_text_position="below" column_spacing="30" portfolio_title_display="title" portfolio_text_alignment="center" portfolio_layout_padding="15px 20px 15px 20px" filters="no" cat_slug="" exclude_cats="" number_posts="8" pagination_type="none" offset="" content_length="excerpt" excerpt_length="0" strip_html="yes" carousel_layout="title_on_rollover" scroll_items="" autoplay="no" show_nav="no" mouse_scroll="no" hide_on_mobile="small-visibility,medium-visibility,large-visibility" class="" id="" animation_type="" animation_direction="down" animation_speed="0.1" animation_offset="" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_color="" background_image="https://placehold.it/2000x938" background_parallax="up" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="center bottom" video_url="" video_aspect_ratio="16:9" video_webm="" video_mp4="" video_ogv="" video_preview_image="" overlay_color="" overlay_opacity="0.5" video_mute="yes" video_loop="yes" fade="no" border_size="0px" border_color="" border_style="solid" padding_top="120px" padding_bottom="100px" padding_left="" padding_right="" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" menu_anchor="" class="" id=""][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" last="yes" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="0% 15%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height=""][fusion_testimonials design="clean" backgroundcolor="transparent" textcolor="#dfdfdf" random="" class="" id=""][fusion_testimonial name="ANSEL ADAMS" avatar="none" image="" image_border_radius="" company="" link="" target="_self"]"When words become unclear, I shall focus with photographs. When images become inadequate, I shall be content with silence." [/fusion_testimonial][fusion_testimonial name="ERNST HASS" avatar="none" image="" image_border_radius="" company="" link="" target="_self"]"There is only you and your camera. The limitations in your photography are in yourself, for what we see is what we are." [/fusion_testimonial][fusion_testimonial name="ROBERT FRANK" avatar="none" image="" image_border_radius="" company="" link="" target="_self"]"Black and white are the colors of photography. They symbolize the alternatives of hope and despair to which mankind is subjected." [/fusion_testimonial][/fusion_testimonials][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]',
      'meta' => 
      array (
        'pyre_demo_slider' => '',
        'pyre_slider_position' => 'default',
        'pyre_slider_type' => 'no',
        'pyre_slider' => '0',
        'pyre_wooslider' => '0',
        'pyre_revslider' => '0',
        'pyre_elasticslider' => '0',
        'pyre_fallback' => '',
        'pyre_avada_rev_styles' => 'default',
        'pyre_main_top_padding' => '',
        'pyre_main_bottom_padding' => '0px',
        'pyre_hundredp_padding' => '',
        'pyre_show_first_featured_image' => 'no',
        'pyre_display_header' => 'yes',
        'pyre_header_100_width' => 'default',
        'pyre_header_bg' => '',
        'pyre_header_bg_color' => '',
        'pyre_header_bg_opacity' => '',
        'pyre_header_bg_full' => 'no',
        'pyre_header_bg_repeat' => 'repeat',
        'pyre_displayed_menu' => 'default',
        'pyre_display_footer' => 'default',
        'pyre_display_copyright' => 'default',
        'pyre_footer_100_width' => 'default',
        'pyre_sidebar_position' => 'default',
        'pyre_sidebar_bg_color' => '',
        'pyre_page_bg_layout' => 'default',
        'pyre_page_bg' => '',
        'pyre_page_bg_color' => '',
        'pyre_page_bg_full' => 'no',
        'pyre_page_bg_repeat' => 'repeat',
        'pyre_wide_page_bg' => 'https://placehold.it/2340x1200',
        'pyre_wide_page_bg_color' => '',
        'pyre_wide_page_bg_full' => 'no',
        'pyre_wide_page_bg_repeat' => 'no-repeat',
        'pyre_portfolio_width_100' => 'no',
        'pyre_portfolio_content_length' => 'default',
        'pyre_portfolio_excerpt' => '',
        'pyre_portfolio_filters' => 'yes',
        'pyre_portfolio_text_layout' => 'default',
        'pyre_portfolio_featured_image_size' => 'default',
        'pyre_portfolio_column_spacing' => '',
        'pyre_page_title' => 'default',
        'pyre_page_title_text' => 'default',
        'pyre_page_title_text_alignment' => 'default',
        'pyre_page_title_100_width' => 'default',
        'pyre_page_title_custom_text' => '',
        'pyre_page_title_text_size' => '',
        'pyre_page_title_custom_subheader' => '',
        'pyre_page_title_custom_subheader_text_size' => '',
        'pyre_page_title_font_color' => '',
        'pyre_page_title_height' => '',
        'pyre_page_title_mobile_height' => '',
        'pyre_page_title_bar_bg' => '',
        'pyre_page_title_bar_bg_retina' => '',
        'pyre_page_title_bar_bg_color' => '',
        'pyre_page_title_bar_borders_color' => '',
        'pyre_page_title_bar_bg_full' => 'default',
        'pyre_page_title_bg_parallax' => 'default',
        'pyre_page_title_breadcrumbs_search_bar' => 'default',
      ),
    ),
     
    array (
      'name' => 'Hire Me',
      'page_template' => '100-width.php',
      'content' => '[fusion_builder_container background_color="" background_image="" background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_url="" video_aspect_ratio="16:9" video_webm="" video_mp4="" video_ogv="" video_preview_image="" overlay_color="" video_mute="yes" video_loop="yes" fade="no" border_size="0px" border_color="" border_style="solid" padding_top="20px" padding_bottom="80px" padding_left="" padding_right="" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" menu_anchor="" class="" id=""][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" last="yes" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="0% 10%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height=""][fusion_text]
<h3 style="text-align: center;">LOOKING FOR BEAUTIFUL IMAGES THAT CAPTURE THE OCCASION?</h3>
[/fusion_text][fusion_text]
<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliqui.</p>
[/fusion_text][/fusion_builder_column][fusion_builder_column type="1_4" layout="1_4" last="no" spacing="yes" center_content="no" hide_on_mobile="yes" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="" margin_top="" margin_bottom="1px" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" element_content="" min_height=""][/fusion_builder_column][fusion_builder_column type="1_2" layout="1_2" last="no" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="" margin_top="" margin_bottom="0" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height=""][fusion_text][contact-form-7 id="165" title="Contact form"][/fusion_text][/fusion_builder_column][fusion_builder_column type="1_4" layout="1_4" last="yes" spacing="yes" center_content="no" hide_on_mobile="yes" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="" margin_top="" margin_bottom="1px" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" element_content="" min_height=""][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container hundred_percent="yes" equal_height_columns="no" menu_anchor="" hide_on_mobile="no" class="" id="" background_color="#25272a" background_image="" background_position="left top" background_repeat="no-repeat" fade="no" background_parallax="none" enable_mobile="no" parallax_speed="0.3" video_mp4="" video_webm="" video_ogv="" video_url="" video_aspect_ratio="16:9" video_loop="yes" video_mute="yes" overlay_color="" video_preview_image="" border_size="0px" border_color="" border_style="solid" margin_top="" margin_bottom="" padding_top="80px" padding_right="4%" padding_bottom="100px" padding_left="4%"][fusion_builder_row][fusion_builder_column type="1_4" layout="1_4" last="no" spacing="yes" center_content="no" hide_on_mobile="yes" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" element_content="" min_height=""][/fusion_builder_column][fusion_builder_column type="1_2" layout="1_2" last="no" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height=""][fusion_title size="3" content_align="center" style_type="single solid" sep_color="" margin_top="" margin_bottom="" class="" id=""]MORE FROM THE AVADA COLLECTION[/fusion_title][/fusion_builder_column][fusion_builder_column type="1_4" layout="1_4" last="yes" spacing="yes" center_content="no" hide_on_mobile="yes" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" element_content="" min_height=""][/fusion_builder_column][fusion_builder_column type="1_1" layout="1_1" background_position="left top" background_color="" border_size="" border_color="" border_style="solid" spacing="yes" background_image="" background_repeat="no-repeat" padding="" margin_top="0px" margin_bottom="0px" class="" id="" animation_type="" animation_speed="0.3" animation_direction="left" hide_on_mobile="no" center_content="no" min_height="none" last="no" hover_type="none" link="" border_position="all"][fusion_portfolio layout="grid-with-text" picture_size="auto" boxed_text="boxed" columns="5" one_column_text_position="below" column_spacing="40" portfolio_title_display="title" portfolio_text_alignment="center" portfolio_layout_padding="15px 20px 15px 20px" filters="no" cat_slug="" exclude_cats="" number_posts="5" pagination_type="none" offset="" content_length="excerpt" excerpt_length="0" strip_html="yes" carousel_layout="title_on_rollover" scroll_items="" autoplay="no" show_nav="yes" mouse_scroll="no" hide_on_mobile="small-visibility,medium-visibility,large-visibility" class="" id="" animation_type="" animation_direction="down" animation_speed="0.1" animation_offset="" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]',
      'meta' => 
      array (
        'pyre_demo_slider' => 'photography-hire-me',
        'pyre_portfolio_width_100' => 'no',
        'pyre_portfolio_content_length' => 'default',
        'pyre_portfolio_excerpt' => '',
        'pyre_portfolio_filters' => 'yes',
        'pyre_portfolio_text_layout' => 'default',
        'pyre_portfolio_featured_image_size' => 'default',
        'pyre_portfolio_column_spacing' => '',
        'pyre_slider_type' => 'flex',
        'pyre_slider' => '0',
        'pyre_wooslider' => 'photography-hire-me',
        'pyre_revslider' => '0',
        'pyre_elasticslider' => '0',
        'pyre_slider_position' => 'default',
        'pyre_avada_rev_styles' => 'default',
        'pyre_fallback' => '',
        'pyre_main_top_padding' => '',
        'pyre_main_bottom_padding' => '0px',
        'pyre_hundredp_padding' => '',
        'pyre_show_first_featured_image' => 'no',
        'pyre_display_header' => 'yes',
        'pyre_header_100_width' => 'default',
        'pyre_header_bg_color' => '',
        'pyre_header_bg_opacity' => '',
        'pyre_header_bg' => '',
        'pyre_header_bg_full' => 'no',
        'pyre_header_bg_repeat' => 'repeat',
        'pyre_displayed_menu' => 'default',
        'pyre_display_footer' => 'default',
        'pyre_display_copyright' => 'default',
        'pyre_footer_100_width' => 'default',
        'pyre_sidebar_position' => 'default',
        'pyre_sidebar_bg_color' => '',
        'pyre_page_bg_layout' => 'default',
        'pyre_page_bg_color' => '',
        'pyre_page_bg' => '',
        'pyre_page_bg_full' => 'no',
        'pyre_page_bg_repeat' => 'repeat',
        'pyre_wide_page_bg_color' => '',
        'pyre_wide_page_bg' => '',
        'pyre_wide_page_bg_full' => 'no',
        'pyre_wide_page_bg_repeat' => 'repeat',
        'pyre_page_title' => 'default',
        'pyre_page_title_breadcrumbs_search_bar' => 'default',
        'pyre_page_title_text' => 'default',
        'pyre_page_title_text_alignment' => 'default',
        'pyre_page_title_custom_text' => '',
        'pyre_page_title_text_size' => '',
        'pyre_page_title_custom_subheader' => '',
        'pyre_page_title_custom_subheader_text_size' => '',
        'pyre_page_title_font_color' => '',
        'pyre_page_title_100_width' => 'default',
        'pyre_page_title_height' => '',
        'pyre_page_title_mobile_height' => '',
        'pyre_page_title_bar_bg_color' => '',
        'pyre_page_title_bar_borders_color' => '',
        'pyre_page_title_bar_bg' => '',
        'pyre_page_title_bar_bg_retina' => '',
        'pyre_page_title_bar_bg_full' => 'default',
        'pyre_page_title_bg_parallax' => 'default',
      ),
    ),
     
    array (
      'name' => 'On Location',
      'page_template' => '100-width.php',
      'content' => '[fusion_builder_container background_color="" background_image="" background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_url="" video_aspect_ratio="16:9" video_webm="" video_mp4="" video_ogv="" video_preview_image="" overlay_color="" video_mute="yes" video_loop="yes" fade="no" border_size="0px" border_color="" border_style="solid" padding_top="50px" padding_bottom="20px" padding_left="" padding_right="" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" menu_anchor="" class="" id=""][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" last="yes" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="0% 15%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height=""][fusion_blog number_posts="" offset="" cat_slug="" exclude_cats="" show_title="yes" title_link="yes" thumbnail="yes" excerpt="yes" excerpt_length="45" meta_all="no" meta_author="yes" meta_categories="yes" meta_comments="yes" meta_date="yes" meta_link="yes" meta_tags="yes" scrolling="pagination" strip_html="yes" blog_grid_columns="3" blog_grid_column_spacing="40" layout="large" class="" id="" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_color="#25272a" background_image="https://placehold.it/2000x938" background_parallax="up" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="center center" video_url="" video_aspect_ratio="16:9" video_webm="" video_mp4="" video_ogv="" video_preview_image="" overlay_color="" video_mute="yes" video_loop="yes" fade="no" border_size="0px" border_color="" border_style="solid" padding_top="100px" padding_bottom="10px" padding_left="" padding_right="" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" menu_anchor="" class="" id=""][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" last="yes" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_size="0px" border_color="" border_style="solid" padding="0% 15%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height=""][fusion_title size="3" content_align="center" style_type="none" sep_color="" margin_top="" margin_bottom="" class="" id=""]SUBSCRIBE TO FOLLOW US ON LOCATION[/fusion_title][fusion_separator style_type="none" top_margin="15" bottom_margin="" sep_color="" border_size="" icon="" icon_circle="" icon_circle_color="" width="" alignment="center" class="" id="" /][fusion_text][contact-form-7 id="633" title="Subscribe"][/fusion_text][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]',
      'meta' => 
      array (
        'pyre_demo_slider' => 'photography-on-location',
        'pyre_portfolio_width_100' => 'no',
        'pyre_portfolio_content_length' => 'default',
        'pyre_portfolio_excerpt' => '',
        'pyre_portfolio_filters' => 'yes',
        'pyre_portfolio_text_layout' => 'default',
        'pyre_portfolio_featured_image_size' => 'default',
        'pyre_portfolio_column_spacing' => '',
        'pyre_slider_type' => 'flex',
        'pyre_slider' => '0',
        'pyre_wooslider' => 'photography-on-location',
        'pyre_revslider' => '0',
        'pyre_elasticslider' => '0',
        'pyre_slider_position' => 'default',
        'pyre_avada_rev_styles' => 'default',
        'pyre_fallback' => '',
        'pyre_main_top_padding' => '',
        'pyre_main_bottom_padding' => '0px',
        'pyre_hundredp_padding' => '',
        'pyre_show_first_featured_image' => 'no',
        'pyre_display_header' => 'yes',
        'pyre_header_100_width' => 'default',
        'pyre_header_bg_color' => '',
        'pyre_header_bg_opacity' => '',
        'pyre_header_bg' => '',
        'pyre_header_bg_full' => 'no',
        'pyre_header_bg_repeat' => 'repeat',
        'pyre_displayed_menu' => 'default',
        'pyre_display_footer' => 'default',
        'pyre_display_copyright' => 'default',
        'pyre_footer_100_width' => 'default',
        'pyre_sidebar_position' => 'default',
        'pyre_sidebar_bg_color' => '',
        'pyre_page_bg_layout' => 'default',
        'pyre_page_bg_color' => '',
        'pyre_page_bg' => '',
        'pyre_page_bg_full' => 'no',
        'pyre_page_bg_repeat' => 'repeat',
        'pyre_wide_page_bg_color' => '',
        'pyre_wide_page_bg' => '',
        'pyre_wide_page_bg_full' => 'no',
        'pyre_wide_page_bg_repeat' => 'repeat',
        'pyre_page_title' => 'default',
        'pyre_page_title_breadcrumbs_search_bar' => 'default',
        'pyre_page_title_text' => 'default',
        'pyre_page_title_text_alignment' => 'default',
        'pyre_page_title_custom_text' => '',
        'pyre_page_title_text_size' => '',
        'pyre_page_title_custom_subheader' => '',
        'pyre_page_title_custom_subheader_text_size' => '',
        'pyre_page_title_font_color' => '',
        'pyre_page_title_100_width' => 'default',
        'pyre_page_title_height' => '',
        'pyre_page_title_mobile_height' => '',
        'pyre_page_title_bar_bg_color' => '',
        'pyre_page_title_bar_borders_color' => '',
        'pyre_page_title_bar_bg' => '',
        'pyre_page_title_bar_bg_retina' => '',
        'pyre_page_title_bar_bg_full' => 'default',
        'pyre_page_title_bg_parallax' => 'default',
      ),
    ),
  ),
);

			return $demos;
		}
		add_filter( 'fusion_builder_get_demo_pages', 'fusion_builder_add_photography_demo' );